import {render,screen,fireEvent,waitFor,act} from '@testing-library/react'
import {beforeAll,beforeEach,expect,it,vi} from 'vitest'
import {LazyTableColumns} from './LazyTableColumns'
import {SCHEMA_INVALIDATED_EVENT} from '../../services/db'
import {LanguageProvider} from '../../state/LanguageContext'
import i18n from '../../i18n'
const api=vi.hoisted(()=>({structure:vi.fn()}))
vi.mock('../../services/db',async original=>({...await original<typeof import('../../services/db')>(),tableStructure:api.structure}))
const shape={comment:'',columns:[{name:'amount',type:'DECIMAL(28,9)',key:'',nullable:true,default:null}],indexes:[],fks:[],triggers:[]}
beforeAll(async()=>{await i18n.changeLanguage('en')})
beforeEach(()=>{api.structure.mockReset().mockResolvedValue(shape)})
it('loads only the expanded exact object and preserves full type precision',async()=>{render(<LanguageProvider><LazyTableColumns connId="c" schema="a.b" table="x.y" sqlActive/></LanguageProvider>);await screen.findByText('DECIMAL(28,9)');expect(api.structure).toHaveBeenCalledWith('c','a.b','x.y');expect(screen.getByText('amount')).toBeInTheDocument()})
it('invalidates field menus when hidden and refreshes after a matching metadata change',async()=>{const view=render(<LanguageProvider><LazyTableColumns ownerKey="visible" connId="c" schema="main" table="orders" sqlActive/></LanguageProvider>);await screen.findByText('amount');fireEvent.contextMenu(screen.getByText('amount'));expect(screen.getByRole('menu')).toBeInTheDocument();view.rerender(<LanguageProvider><LazyTableColumns ownerKey="hidden" connId="c" schema="main" table="orders" sqlActive/></LanguageProvider>);expect(screen.queryByRole('menu')).toBeNull();act(()=>window.dispatchEvent(new CustomEvent(SCHEMA_INVALIDATED_EVENT,{detail:{connId:'other'}})));expect(api.structure).toHaveBeenCalledTimes(1);api.structure.mockResolvedValue({...shape,columns:[{...shape.columns[0],name:'updated'}]});act(()=>window.dispatchEvent(new CustomEvent(SCHEMA_INVALIDATED_EVENT,{detail:{connId:'c'}})));await screen.findByText('updated');expect(screen.queryByText('amount')).toBeNull()})
it('shows metadata failure, retries, and ignores late results from an old owner',async()=>{api.structure.mockRejectedValueOnce(new Error('metadata unavailable'));const view=render(<LanguageProvider><LazyTableColumns connId="c" schema="main" table="a" sqlActive={false}/></LanguageProvider>);await screen.findByRole('alert');fireEvent.click(screen.getByText('Retry'));await screen.findByText('amount');let resolve!:(v:unknown)=>void;api.structure.mockReturnValueOnce(new Promise(ok=>{resolve=ok}));view.rerender(<LanguageProvider><LazyTableColumns connId="old" schema="main" table="a" sqlActive={false}/></LanguageProvider>);view.rerender(<LanguageProvider><LazyTableColumns connId="new" schema="main" table="b" sqlActive={false}/></LanguageProvider>);await waitFor(()=>expect(screen.getByText('amount')).toBeInTheDocument());await act(async()=>{resolve({...shape,columns:[{...shape.columns[0],name:'stale'}]})});expect(screen.queryByText('stale')).toBeNull()})
